name: Docker BuildX
on: push

jobs:
  docker-buildx:
    strategy:
      matrix:
          arch: [amd64, arm64]
          os: [ubuntu:18.04, ubuntu:20.04]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "OS=${{ matrix.os }}, ARCHITECTURE=${{ matrix.arch }}"

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          build-args: BASE_IMAGE=${{ matrix.os }}
          context: .
          file: Dockerfile.${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: atsushisaito/practice-docker-github-action:latest-${{ matrix.arch }}
